# Spring的配置文件数据库:
spring:
  datasource:
    url: jdbc:mysql://60.205.230.70:3306/pe6?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    password: root
    username: root
  redis:
    host: 60.205.230.70
    password: root
    port: 6379
  rabbitmq:
    host: 60.205.230.70
    username: root
    password: root
    port: 5672
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
    encoder-name:
  application:
    name: oa-service